name: geo_utils
description: A utility library to handle Geo data in Dart.
version: 1.0.0
homepage: https://github.com/thib92/dart_geo

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  geohash: ^0.2.1

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
